
version: 2.1
jobs:
  build:
    working_directory: ~/marketplace
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - run:
          name: test markeplace application
          command: yarn global add jest && yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
